export default [
  'Acorn TV',
  'AMC+',
  'Amazon Prime Video',
  'Apple TV',
  'BritBox',
  'Criterion Channel',
  'Crunchyroll',
  'Disney Plus',
  'Discovery+',
  'ESPN Plus',
  'fuboTV',
  'HBO Max',
  'Hoopla',
  'Hulu',
  'Kanopy',
  'MGM Plus',
  'Netflix',
  'Paramount Plus Premium',
  'Peacock Premium',
  'Philo',
  'Pluto TV',
  'Shudder',
  'Starz',
  'The Roku Channel',
  'Tubi TV',
  'YouTube Premium',
  'YouTube TV',
];
